### ISSUE TITLE
how to use in fragment ?

### ISSUE THREAD

**Issue by birjubhatt** [mattsilber/sigcap#3]
i want implement in fragment 
` 

      @Override
       public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        root = (ViewGroup) inflater.inflate(R.layout.fragment_work_order_detail, null);

  
        woImgSignature.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new SignatureDialogBuilder()
                        .show(getActivity(), new SignatureDialogBuilder.SignatureEventListener() {
                            @Override
                            public void onSignatureEntered(File savedFile) {
                                new ImageRequest(getActivity(),root.findViewById(R.id.wo_img_signature))
                                        .setTargetFile(savedFile)
                                        .setFadeTransition()
                                        .execute(); // Just showing the image

                            }

                            @Override
                            public void onSignatureInputCanceled() {
                                Toast.makeText(getActivity(), "Signature input canceled", Toast.LENGTH_SHORT)
                                        .show();
                            }

                            @Override
                            public void onSignatureInputError(Throwable e) {
                                if (e instanceof NoSignatureException) // They clicked confirm without entering anything
                                // doSomethingOnNoSignatureEntered();
                                {

                                } else {
                                    Toast.makeText(getActivity(), "Signature error", Toast.LENGTH_SHORT)
                                            .show();
                                }
                            }
                        });
            }
        });

        return root;
    }`
in this 

 public void onSignatureEntered(File savedFile) {
                                new ImageRequest(getActivity(),root.findViewById(R.id.wo_img_signature))

i got error can not resolved counstructor

![Screenshot from 2019-05-07 12-30-53](https://user-images.githubusercontent.com/21102131/57278562-6c09e700-70c4-11e9-9ac0-b0f1608f5dc2.png)

**Comment by mattsilber** [comment]
`ImageRequest` is from [another repo](https://github.com/mattsilber/imageloader) of mine and is just used for showing the Bitmap, and not relevant to capturing the signature at all. You can use any lazy image loader or just set the Bitmap to your ImageView directly.

**Comment by birjubhatt** [comment]
@Override
        public void onSignatureEntered(File savedFile) {
          Bitmap myBitmap = BitmapFactory.decodeFile(savedFile.getAbsolutePath());
          woImgSignature1.setImageBitmap(myBitmap);
      }

**Comment by birjubhatt** [comment]
can we use this selected image in again open popup ? whenever i click image and open popup that time blank image is display
